IMDB-BINARY:
  lr: 0.00015
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 0
  weight_decay_f: 0
  max_epoch: 80
  max_epoch_f: 500
  mask_rate: 0.5
  mask_rate: 0.25
  num_layers: 4
  trans_num_layers: 2
  enc_type: normal
  dec_type: mlp
  num_subgraph: 2
  subgraph_lambda: 2
  pe_dim: 32
  kd_alpha: 0.01
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  drop_edge_rate: 0.0
  alpha_l: 1
  norm: batchnorm
  residual: False
  scheduler: False
  linear_prob: True
  pooling: mean
  batch_size: 64
  alpha_l: 1
IMDB-MULTI:
  lr: 0.00015
  num_hidden: 512
  num_heads: 2
  weight_decay: 0
  max_epoch: 60
  mask_rate: 0.5
  num_layers: 3
  trans_num_layers: 3
  enc_type: parallel
  dec_type: mlp
  num_subgraph: 4
  subgraph_lambda: 2
  pe_dim: 32
  kd_alpha: 0.1
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  drop_edge_rate: 0.0
  alpha_l: 1
  norm: batchnorm
  scheduler: False
  linear_prob: True
  pooling: mean
  batch_size: 128
  alpha_l: 1
PROTEINS:
  lr: 0.00015
  num_hidden: 512
  weight_decay: 0
  max_epoch: 120
  mask_rate: 0.5
  num_layers: 4
  trans_num_layers: 1
  enc_type: parallel
  dec_type: mlp
  num_subgraph: 2
  subgraph_lambda: 2
  pe_dim: 24
  kd_alpha: 100.0
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  drop_edge_rate: 0.0
  alpha_l: 1
  norm: batchnorm
  scheduler: False
  linear_prob: True
  pooling: max
  batch_size: 128
  norm: batchnorm
  alpha_l: 1
MUTAG:
  num_hidden: 32
  num_layers: 5
  lr: 0.0005
  weight_decay: 0.00
  drop_edge_rate: 0.0
  max_epoch: 20
  mask_rate: 0.75
  num_layers: 5
  trans_num_layers: 2
  enc_type: normal
  dec_type: gnn
  num_subgraph: 0
  subgraph_lambda: 2
  pe_dim: 16
  kd_alpha: 1.0
  encoder: gin
  decoder: gin
  activation: prelu
  loss_fn: sce
  scheduler: False  
  pooling: sum
  batch_size: 64
  alpha_l: 2
  replace_rate: 0.1
  norm: batchnorm
  in_drop: 0.2
  attn_drop: 0.1
  alpha_l: 2
REDDIT-BINARY:
  lr: 0.00015
  weight_decay: 0.0
  max_epoch: 100
  drop_edge_rate: 0.0
  num_hidden: 512
  mask_rate: 0.75
  num_layers: 2
  trans_num_layers: 3
  enc_type: parallel
  dec_type: gnn
  num_subgraph: 2
  subgraph_lambda: 2
  pe_dim: 16
  kd_alpha: 1.0
  encoder: gin
  decoder: gin
  activation: prelu
  pooling: sum
  scheduler: True
  batch_size: 32
  replace_rate: 0.1
  norm: layernorm
  loss_fn: sce
  alpha_l: 2
COLLAB:
  lr: 0.00015
  weight_decay: 0.0
  max_epoch: 20
  num_layers: 2
  num_hidden: 256
  mask_rate: 0.75
  num_layers: 2
  trans_num_layers: 3
  enc_type: normal
  dec_type: gnn
  num_subgraph: 2
  subgraph_lambda: 2
  pe_dim: 16
  kd_alpha: 1.0
  drop_edge_rate: 0.0
  activation: relu
  encoder: gin
  decoder: gin
  scheduler: True
  pooling: max
  batch_size: 64
  loss_fn: sce
  norm: batchnorm
  alpha_l: 1
NCI1:
  lr: 0.001
  max_epoch: 300
  num_layers: 2
  num_hidden: 512
  mask_rate: 0.25
  num_layers: 2
  trans_num_layers: 3
  enc_type: normal
  dec_type: mlp
  num_subgraph: 0
  subgraph_lambda: 2
  pe_dim: 32
  kd_alpha: 100.0
  drop_edge_rate: 0.0
  activation: prelu
  encoder: gin
  decoder: gin
  scheduler: True
  pool: sum
  batch_size: 64
  alpha_l: 2
  replace_rate: 0.1
  norm: batchnorm
  loss_fn: sce
  alpha_l: 2
