cora:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.4
  num_layers: 2
  encoder: gat
  decoder: gat 
  num_hops: 1
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce 
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.05 
  alpha_l: 3
  scheduler: True
  batch_size: 1024
  pooling: centroid
citeseer:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 2
  num_layers: 3
  num_hops: 1
  weight_decay: 2e-5
  weight_decay_f: 0.01
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.25
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2  
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.1
  alpha_l: 1 
  scheduler: True
  residual: True
  batch_size: 1024
  pooling: max
pubmed:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  num_hops: 1
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 400
  max_epoch_f: 300
  mask_rate: 0.3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
  batch_size: 64
  pooling: mean
Physics:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 3
  num_hops: 1
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
  batch_size: 16
  pooling: sum
CS:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 4
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.3
  num_hops: 1
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
  pooling: max
  batch_size: 128
Photo:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 1024
  num_heads: 4
  num_layers: 3
  num_hops: 1
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  max_epoch: 300
  max_epoch_f: 300
  mask_rate: 0.6
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
  pooling: sum
  batch_size: 128
